version: '3'
services:
  service1_1:
    build:
      context: .
      dockerfile: Dockerfile_service1
    expose:
      - "8199"
    depends_on:
      - service2
    networks:
      - app-network
    labels:
      - "com.docker.compose.project=exercise_4"

  service1_2:
    build:
      context: .
      dockerfile: Dockerfile_service1
    expose:
      - "8199"
    depends_on:
      - service2
    networks:
      - app-network
    labels:
      - "com.docker.compose.project=exercise_4"

  service1_3:
    build:
      context: .
      dockerfile: Dockerfile_service1
    expose:
      - "8199"
    depends_on:
      - service2
    networks:
      - app-network
    labels:
      - "com.docker.compose.project=exercise_4"

  service2:
    build:
      context: .
      dockerfile: Dockerfile_service2
    expose:
      - "8200"
    networks:
      - app-network
    labels:
      - "com.docker.compose.project=exercise_4"

  nginx:
    image: nginx:alpine
    ports:
      - "8198:8198"
    command: >
      sh -c "echo 'events {
          worker_connections 1024;
      }

      http {
          upstream service1_backend {
              server service1_1:8199;
              server service1_2:8199;
              server service1_3:8199;
          }

          server {
              listen 8198;
              
              auth_basic \"Restricted Access\";
              auth_basic_user_file /etc/nginx/.passwd;

              location = / {
                  default_type text/html;
                  return 200 '\''<!DOCTYPE html>
      <html>
      <head>
          <title>System Monitor</title>
          <style>
              body {
                  font-family: Arial, sans-serif;
                  max-width: 800px;
                  margin: 20px auto;
                  padding: 20px;
              }
              textarea {
                  width: 100%;
                  height: 400px;
                  margin: 20px 0;
                  font-family: monospace;
              }
              button {
                  padding: 10px 20px;
                  margin-right: 10px;
                  font-size: 16px;
                  cursor: pointer;
              }
          </style>
      </head>
      <body>
          <h1>System Monitor</h1>
          <div>
              <button onclick=\"sendRequest()\">REQUEST</button>
              <button onclick=\"stopSystem()\">STOP</button>
          </div>
          <textarea id=\"responseArea\" readonly></textarea>

          <script>
              async function sendRequest() {
                  try {
                      const response = await fetch(\"/api/status\");
                      const data = await response.text();
                      document.getElementById(\"responseArea\").value = data;
                  } catch (error) {
                      document.getElementById(\"responseArea\").value = \"Error: \" + error.message;
                  }
              }

              async function stopSystem() {
                  try {
                      await fetch(\"/stop\", { method: \"POST\" });
                      document.getElementById(\"responseArea\").value = \"System is shutting down...\";
                  } catch (error) {
                      document.getElementById(\"responseArea\").value = \"Error stopping system: \" + error.message;
                  }
              }
          </script>
      </body>
      </html>'\'';
              }
              
              location /api/status {
                  proxy_pass http://service1_backend;
              }
              
              location /stop {
                  proxy_pass http://shutdown-handler:8201;
              }
          }
      }' > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    volumes:
      - /home/nix/git/compse140/exercise_4/login.txt:/etc/nginx/.passwd:ro
    depends_on:
      - service1_1
      - service1_2
      - service1_3
      - shutdown-handler
    networks:
      - app-network
    labels:
      - "com.docker.compose.project=exercise_4"

  shutdown-handler:
    build:
      context: .
      dockerfile: Dockerfile_shutdown
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - "8201"
    networks:
      - app-network
    labels:
      - "com.docker.compose.project=exercise_4"

networks:
  app-network:
    driver: bridge
