version: '3'
services:
  service1_1:
    build:
      context: .
      dockerfile: Dockerfile_service1
    expose:
      - "8199"
    depends_on:
      - service2
    networks:
      - app-network
    labels:
      - "com.docker.compose.project=exercise_4"

  service1_2:
    build:
      context: .
      dockerfile: Dockerfile_service1
    expose:
      - "8199"
    depends_on:
      - service2
    networks:
      - app-network
    labels:
      - "com.docker.compose.project=exercise_4"

  service1_3:
    build:
      context: .
      dockerfile: Dockerfile_service1
    expose:
      - "8199"
    depends_on:
      - service2
    networks:
      - app-network
    labels:
      - "com.docker.compose.project=exercise_4"

  service2:
    build:
      context: .
      dockerfile: Dockerfile_service2
    expose:
      - "8200"
    networks:
      - app-network
    labels:
      - "com.docker.compose.project=exercise_4"

  nginx:
    image: nginx:alpine
    ports:
      - "8198:8198"
    command: /bin/sh -c "echo 'events { worker_connections 1024; } http { upstream service1_backend { server service1_1:8199; server service1_2:8199; server service1_3:8199; } server { listen 8198; auth_basic \"Restricted Access\"; auth_basic_user_file /etc/nginx/passwd; location / { root /usr/share/nginx/html; index index.html; } location /api/status { proxy_pass http://service1_backend; } location /stop { proxy_pass http://shutdown-handler:8201; } } }' > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./login.txt:/etc/nginx/passwd:ro
    depends_on:
      - service1_1
      - service1_2
      - service1_3
      - shutdown-handler
    networks:
      - app-network
    labels:
      - "com.docker.compose.project=exercise_4"

  shutdown-handler:
    build:
      context: .
      dockerfile: Dockerfile_shutdown
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - "8201"
    networks:
      - app-network
    labels:
      - "com.docker.compose.project=exercise_4"

networks:
  app-network:
    driver: bridge
